version: '3'

services:
  web:
    build: ./web_app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build: ./db
  #mongodb:
  #  image: 'mongo'
  #  container_name: 'mongo_container'
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: admin
  #    MONGO_INITDB_ROOT_PASSWORD: password
  #    MONGO_INITDB_DATABASE: mongoTestDB
  #  volumes:
  #    - ./init-mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
  #    - ./mongo-volume:/data/db
  #  ports:
  #    - '27017-27019:27017-27019'
